# Generated by Django 2.2.7 on 2020-01-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comments',
            field=models.CharField(max_length=20),
        ),
    ]
