# Generated by Django 2.2.7 on 2020-01-21 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200120_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamePrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.URLValidator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.URLValidator]),
            preserve_default=False,
        ),
    ]
