# Generated by Django 2.2.7 on 2020-01-21 18:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=30)),
                ('comments', models.PositiveIntegerField()),
                ('rate', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('plataform', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=500, validators=[django.core.validators.URLValidator])),
                ('picture', models.CharField(max_length=500, validators=[django.core.validators.URLValidator])),
                ('gamePrice', models.FloatField()),
            ],
        ),
    ]
